### ISSUE TITLE
Token in cookies

### ISSUE THREAD

**Issue by marcofucci** [uktrade/export-wins-ui#1]
It seems like the token is stored in a cookie in plain text.

A better implementation would be to sign and encrypt the token so that it can't be used in any attacks.

@munhitsu that do you think?

**Comment by danielquinn** [comment]
This sounds like a good idea to me, though it does complicate things a bit since it would involve hacking out parts of DRF's `TokenAuthorisation` (or whatever it's called) class.  Is this a deal-breaker or can it wait 'till a later sprint?

**Comment by marcofucci** [comment]
It depends on the risk owners and the business. Do you know @munhitsu ?

Just to be clear, it does not involve `TokenAuthorisation` as this is the UI bit and you store/retrieve cookies in your code.

**Comment by danielquinn** [comment]
Ah you're suggesting we tweak how the UI handles the token and then passes the decrypted token down to the data server, not transparently pass the encrypted cookie down to the data server and then have that decrypt it.  Sure, that would be a lot easier as you're right, this is all done manually at the moment.

**Comment by marcofucci** [comment]
yep :)
